readme.txt

forgot to update the dev Stable tag

forgot to update the dev Stable tag

---

README.md
accelerated-moblie-pages.php
readme.txt
themes/default/functions.php
themes/default/header.php
themes/default/index.php

0.7 Release

---

includes/options/options-init.php
templates/single.php

Replacing #106 with this new pull for cleaner commits.

New: Fixing the Facebook share button.

---

accelerated-moblie-pages.php
templates/features.php

0.8.4 beta branch merge

---

README.md
accelerated-moblie-pages.php
includes/options/options-init.php
readme.txt
templates/features.php
templates/single.php

0.8.5.1 Release

---

accelerated-moblie-pages.php

Version number updated from 0.8.8 beta to 0.8.8

0.8.8 - update Version number

---

includes/newsletter.php
includes/options/options-init.php
templates/custom-amp-content.php
templates/design-manager/design-1/elements/comments.php
templates/design-manager/design-1/elements/related-posts.php
templates/design-manager/design-1/elements/social-icons.php
templates/design-manager/design-1/footer.php
templates/design-manager/design-1/frontpage.php
templates/design-manager/design-1/index.php
templates/design-manager/design-1/single.php
templates/design-manager/design-1/style.php
templates/design-manager/design-2/elements/comments.php
templates/design-manager/design-2/elements/related-posts.php
templates/design-manager/design-2/elements/social-icons.php
templates/design-manager/design-2/frontpage.php
templates/design-manager/design-2/index.php
templates/design-manager/design-2/single.php
templates/design-manager/design-2/style.php
templates/features.php

All the tasks done in Milestone 0.9.32

All the tasks done in Milestone 0.9.32

---

accelerated-moblie-pages.php
includes/options/redux-framework/framework.php
readme.txt
templates/design-manager.php
templates/design-manager/design-1/elements/related-posts.php
templates/design-manager/design-1/index.php
templates/design-manager/design-1/style.php
templates/design-manager/design-2/elements/related-posts.php
templates/design-manager/design-2/footer.php
templates/design-manager/design-2/index.php
templates/design-manager/design-2/style.php
templates/design-manager/empty-filter.php
templates/features.php

0.9.33 Release

---

accelerated-moblie-pages.php
includes/options/options-init.php
readme.txt
templates/design-manager.php
templates/design-manager/design-1/elements/comments.php
templates/design-manager/design-1/elements/simple-comment-button.php
templates/design-manager/design-1/frontpage.php
templates/design-manager/design-1/single.php
templates/design-manager/design-1/style.php
templates/design-manager/design-2/elements/comments.php
templates/design-manager/design-2/elements/simple-comment-button.php
templates/design-manager/design-2/frontpage.php
templates/design-manager/design-2/index.php
templates/design-manager/design-2/single.php
templates/design-manager/design-2/style.php
templates/features.php

0.9.35 update done

---

includes/options/admin-config.php
templates/design-manager/design-1/archive.php
templates/design-manager/design-1/elements/comments.php
templates/design-manager/design-1/elements/content.php
templates/design-manager/design-1/elements/related-posts.php
templates/design-manager/design-1/elements/social-icons.php
templates/design-manager/design-1/frontpage.php
templates/design-manager/design-1/index.php
templates/design-manager/design-1/style.php
templates/design-manager/design-2/elements/comments.php
templates/design-manager/design-2/elements/related-posts.php
templates/design-manager/design-2/elements/social-icons.php
templates/design-manager/design-2/frontpage.php
templates/design-manager/design-2/index.php
templates/design-manager/design-2/style.php
templates/features.php

Merging branch 0.9.41 to master 
More details about 0.9.41 https://github.com/ahmedkaludi/accelerated-mobile-pages/milestone/23

Merging branch 0.9.41 to master

---

templates/design-manager/design-3/style.php

fix design 3 header top alignment

---

templates/features.php

Development to Development 0.9.57

Development to Development 0.9.57

---

accelerated-moblie-pages.php
readme.txt
templates/design-manager/design-2/style.php
templates/features.php

Development 0.9.57.1

---

accelerated-moblie-pages.php
readme.txt
templates/design-manager/design-3/functions.php
templates/design-manager/design-3/style.php
templates/features.php

Development 0.9.58.1

---

accelerated-moblie-pages.php
classes/class-ampforwp-youtube-embed.php
includes/options/admin-config.php
includes/redirect.php
readme.txt
templates/customizer/assets/customizer-preview.js
templates/customizer/customizer-new.php
templates/customizer/customizer.php
templates/design-manager.php
templates/design-manager/design-1/elements/bread-crumbs.php
templates/design-manager/design-1/header-bar.php
templates/design-manager/design-1/single.php
templates/design-manager/design-1/style.php
templates/design-manager/design-2/elements/bread-crumbs.php
templates/design-manager/design-2/header-bar.php
templates/design-manager/design-2/single.php
templates/design-manager/design-2/style.php
templates/design-manager/design-3/elements/bread-crumbs.php
templates/design-manager/design-3/functions.php
templates/design-manager/design-3/header-bar.php
templates/design-manager/design-3/single.php
templates/design-manager/design-3/style.php
templates/features.php
templates/instant-articles/instant-article.php

Development 0.9.60

---

includes/redirect.php

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1146

validation for session in php

---

accelerated-moblie-pages.php
components/comments/comments.php
components/logo/logo.php
includes/options/admin-config.php
includes/options/extensions/amp_slider/amp_slider/field_amp_slider.js
includes/redirect.php
includes/thirdparty-compatibility.php
includes/vendor/amp/includes/class-amp-post-template.php
includes/vendor/vendor-changelog.txt
pagebuilder/amp-page-builder.php
pagebuilder/functions.php
pagebuilder/inc/adminAjaxContents.php
pagebuilder/inc/viewShowFrontData.php
pagebuilder/modules/contents-module.php
readme.txt
templates/design-manager/design-1/style.php
templates/design-manager/design-2/style.php
templates/design-manager/design-3/style.php
templates/features.php

W6 release candidate

---

includes/options/admin-config.php

Removed beta code #1661

---

includes/vendor/amp/includes/sanitizers/class-amp-blacklist-sanitizer.php

Null check added to fix null reference exception

Null check added to fix null reference exception

---

templates/features.php

Add missed prefix in the function #2886

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/admin-style.css
includes/features/advertisement/ads-options.php
includes/features/functions.php
includes/module-upgrade.js
includes/modules-upgrade.php
includes/options/admin-config.php
readme.txt
templates/features.php

0.9.98.11 update code merge into master

0.9.98.11 update code merge into master

---

templates/design-manager.php
templates/design-manager/swift/style.php

1.0.2 code added in Master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/analytics/analytics-functions.php
readme.txt

1.0.6 update merge 1.0+ branch into master

1.0.6 update merge 1.0+ branch into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
readme.txt
templates/features.php

1.0.8 merged into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/performance/performance-functions.php
includes/vendor/amp/includes/class-amp-post-template.php
includes/vendor/amp/includes/sanitizers/class-amp-blacklist-sanitizer.php
readme.txt
templates/features.php

1.0.9 update merge into master

1.0.9 update merge into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/comments/comments.php
components/search/search.php
includes/features/analytics/analytics-functions.php
includes/features/analytics/analytics-options.php
includes/features/functions.php
includes/features/performance/performance-functions.php
includes/features/push-notification/push-notification-functions.php
includes/options/admin-config.php
includes/options/redux-core/assets/css/redux-admin.css
readme.txt
templates/design-manager/design-1/style.php
templates/design-manager/design-3/style.php
templates/design-manager/swift/style.php
templates/features.php

1.0.13 merge into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/options/admin-config.php
readme.txt
templates/features.php

1.0.14 merge into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/theme-loader.php
readme.txt

Merge 1.0.21 in master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/components-core.php
readme.txt

Merge 1.0.25 in to master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/admin-script.js
includes/admin-style.css
includes/options/admin-config.php
includes/options/redux-core/framework.php
includes/options/redux-core/inc/extensions/import_export/import_export/field_import_export.php
includes/options/redux-core/templates/panel/menu_container.tpl.php
readme.txt
templates/design-manager/swift/page.php

Merge 1.0.26 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/gdpr/gdpr.php
components/loop/loop.php
includes/admin-script.js
includes/features/performance/performance-functions.php
includes/options/admin-config.php
includes/options/redux-core/framework.php
includes/vendor/amp/includes/sanitizers/class-amp-allowed-tags-generated.php
includes/vendor/amp/includes/sanitizers/class-amp-blacklist-sanitizer.php
includes/vendor/vendor-changelog.txt
pagebuilder/components/modulePopupTemplate.php
pagebuilder/inc/admin-amp-page-builder.js
pagebuilder/inc/viewShowFrontData.php
readme.txt
templates/design-manager/design-1/elements/social-icons.php
templates/design-manager/design-2/elements/social-icons.php
templates/design-manager/swift/footer.php
templates/design-manager/swift/page.php
templates/design-manager/swift/style.php
templates/features.php

Merge 1.0.27 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/components-core.php
includes/admin-script.js
includes/features/advertisement/ads-functions.php
includes/features/performance/performance-functions.php
includes/options/admin-config.php
includes/redirect.php
includes/thirdparty-compatibility.php
pagebuilder/modules/cta-mod-module.php
readme.txt
templates/design-manager/design-1/elements/content.php
templates/design-manager/design-1/footer.php
templates/design-manager/design-2/elements/content.php
templates/design-manager/design-2/footer.php
templates/design-manager/design-3/elements/content.php
templates/design-manager/design-3/footer.php
templates/design-manager/swift/footer.php
templates/design-manager/swift/single.php
templates/features.php

Merge 1.0.32  update into master

Merge 1.0.32  update into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/author-box/author-box.php
components/components-core.php
components/related-posts/related-posts.php
includes/features/functions.php
includes/features/performance/performance-functions.php
includes/options/admin-config.php
includes/thirdparty-compatibility.php
readme.txt
templates/design-manager/design-1/elements/featured-image.php
templates/design-manager/design-1/elements/related-posts.php
templates/design-manager/design-2/elements/featured-image.php
templates/design-manager/design-2/elements/related-posts.php
templates/design-manager/design-2/style.php
templates/design-manager/design-3/elements/featured-image.php
templates/design-manager/design-3/elements/related-posts.php
templates/design-manager/swift/style.php
templates/features.php

Merge 1.0.36 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
classes/class-ampforwp-infinite-scroll.php
components/author-box/author-box.php
components/components-core.php
components/related-posts/related-posts.php
feeds/instant-article-feed.php
includes/admin-style.css
includes/features/push-notification/push-notification-functions.php
includes/features/push-notification/push-notification-options.php
includes/features/structure-data/structured-data-functions.php
includes/options/admin-config.php
includes/thirdparty-compatibility.php
pagebuilder/inc/viewShowFrontData.php
readme.txt
templates/design-manager/design-1/elements/related-posts.php
templates/design-manager/design-1/style.php
templates/design-manager/design-2/elements/related-posts.php
templates/design-manager/design-2/style.php
templates/design-manager/design-3/elements/related-posts.php
templates/design-manager/design-3/style.php
templates/design-manager/swift/single.php
templates/design-manager/swift/style.php
templates/features.php
templates/instant-articles/instant-article.php
templates/woo-widget.php

merge 1.0.37 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/gdpr/gdpr.php
includes/features/functions.php
includes/features/structure-data/structured-data-functions.php
readme.txt
templates/features.php

Merge 1.0.45 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/loop/loop.php
includes/admin-style.css
includes/features/push-notification/push-notification-functions.php
includes/features/structure-data/structured-data-functions.php
includes/options/admin-config.php
includes/vendor/amp/includes/amp-post-template-actions.php
pagebuilder/modules/contents-module.php
readme.txt
templates/features.php

Merge 1.0.47 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/components-core.php
components/gdpr/gdpr.php
includes/admin-script.js
includes/features/functions.php
includes/newsletter.php
includes/vendor/amp/includes/amp-post-template-actions.php
pagebuilder/config/moduleTemplate.php
pagebuilder/modules/contents-module.php
readme.txt
templates/features.php

Merge 1.0.48 update into master

Merge 1.0.48 update into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
pagebuilder/config/moduleTemplate.php
readme.txt

Merge 1.0.49 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
readme.txt
templates/features.php

Merge 1.0.54.1 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/gdpr/gdpr.php
readme.txt
templates/features.php
templates/template-mode/template-mode.php

Merge 1.0.57 in to master

---

README.md
accelerated-moblie-pages.php
changelog.txt
classes/class-ampforwp-photo-gallery-embed.php
components/comments/comments.php
includes/features/analytics/analytics-functions.php
includes/features/analytics/analytics-options.php
includes/features/contact-form/contact-form-options.php
includes/features/performance/performance-functions.php
pagebuilder/inc/viewShowFrontData.php
readme.txt
templates/design-manager/swift/single.php
templates/design-manager/swift/style.php
templates/features.php

Merge 1.0.58.1 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
readme.txt
templates/design-manager/swift/style.php
templates/features.php

Merge 1.0.58.2 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php
readme.txt

Merge 1.0.58.3 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/performance/performance-functions.php
readme.txt

Merge 1.0.58.4 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/functions.php
includes/features/structure-data/structured-data-functions.php
includes/thirdparty-compatibility.php
readme.txt
templates/template-mode/template-mode.php

merge 1.0.58.5 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/performance/performance-functions.php
includes/options/redux-core/framework.php
readme.txt
templates/design-manager/swift/style.php

Merge 1.0.61.2 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
classes/class-ampforwp-infinite-scroll.php
components/breadcrumb/breadcrumb.php
components/categories-tags/categories-tags.php
includes/features/performance/performance-functions.php
includes/options/admin-config.php
includes/options/redux-core/inc/class.redux_helpers.php
includes/thirdparty-compatibility.php
pagebuilder/inc/viewShowFrontData.php
pagebuilder/modules/accordion-mod-module.php
pagebuilder/modules/list-mod-module.php
readme.txt
templates/design-manager/design-1/footer.php
templates/design-manager/design-1/style.php
templates/design-manager/design-2/footer.php
templates/design-manager/design-3/footer.php
templates/design-manager/swift/footer.php
templates/design-manager/swift/page.php
templates/design-manager/swift/single.php
templates/design-manager/swift/style.php
templates/features.php

Merge 1.0.62 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/performance/performance-functions.php
includes/modules/js/amp.js
readme.txt
templates/features.php

merge 1.0.62.1 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer-5-3.php
pagebuilder/inc/admin-amp-page-builder.js
pagebuilder/inc/viewShowFrontData.php
pagebuilder/modules/accordion-mod-module.php
readme.txt
templates/design-manager/swift/style.php

merge 1.0.62.2 in to master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/components-core.php
includes/features/performance/performance-functions.php
includes/features/push-notification/push-notification-options.php
includes/thirdparty-compatibility.php
pagebuilder/config/moduleTemplate.php
pagebuilder/modules/contact-form-shortcode-module.php
readme.txt
templates/design-manager/design-2/style.php
templates/design-manager/design-3/style.php
templates/design-manager/swift/single.php
templates/design-manager/swift/style.php
templates/features.php

Merge 1.0.68.1 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
readme.txt
templates/features.php

1.0.69.2 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/components-core.php
includes/features/pagebuilders-support/pagebuilders_support.php
includes/options/admin-config.php
readme.txt
templates/design-manager/design-1/single.php
templates/design-manager/design-2/single.php
templates/design-manager/design-3/single.php

Merge 1.0.74 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
classes/class-ampforwp-infinite-scroll.php
components/breadcrumb/breadcrumb.php
components/components-core.php
includes/options/admin-config.php
readme.txt
templates/design-manager/design-3/style.php
templates/features.php

Merge 1.0.76.11 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
readme.txt
templates/features.php

merge 1.0.76.12 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/breadcrumb/breadcrumb.php
includes/admin-script.js
includes/features/performance/performance-functions.php
includes/options/redux-core/assets/css/redux-admin.css
includes/options/redux-core/inc/fields/select/field_select.php
includes/options/redux-core/templates/panel/footer.tpl.php
includes/updater/update.php
readme.txt
templates/design-manager/swift/single.php
templates/features.php

merge 1.0.77.6 into master 

---

README.md
accelerated-moblie-pages.php
changelog.txt
classes/class-ampforwp-slide-anything-embed.php
components/categories-tags/categories-tags.php
components/comments/comments.php
components/loop/loop.php
includes/admin-script.js
includes/ampforwp-fields-array.php
includes/features/functions.php
includes/features/performance/performance-functions.php
includes/options/admin-config.php
includes/options/redux-core/framework.php
includes/vendor/amp/includes/amp-post-template-actions.php
includes/vendor/aq_resizer.php
readme.txt
templates/amp-code-widget.php
templates/design-manager/swift/style.php
templates/features.php
templates/instant-articles/instant-article-sanitizer.php

Merge 1.0.77.9 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/comments/comments.php
components/components-core.php
components/logo/logo.php
components/related-posts/related-posts.php
includes/features/analytics/analytics-functions.php
readme.txt
templates/design-manager/swift/single.php
templates/design-manager/swift/style.php

merge 1.0.77.10 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
components/components-core.php
includes/options/redux-core/assets/css/redux-admin.css
includes/redirect.php
readme.txt

merge 1.0.77.19 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/functions.php
includes/thirdparty-compatibility.php
readme.txt
templates/features.php

Merge 1.0.77.20 int0 master

---

README.md
accelerated-moblie-pages.php
changelog.txt
feeds/instant-article-feed.php
includes/features/advertisement/ads-functions.php
includes/features/advertisement/ads-options.php
includes/features/analytics/analytics-functions.php
includes/features/analytics/analytics-options.php
includes/features/functions.php
includes/options/admin-config.php
includes/thirdparty-compatibility.php
includes/vendor/amp/includes/utils/class-amp-image-dimension-extractor.php
readme.txt
templates/features.php

Merge 1.0.77.23 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
pagebuilder/inc/amppb_save_data.php
pagebuilder/inc/viewShowFrontData.php
readme.txt

Merge 1.0.77.32 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/performance/performance-functions.php
includes/options/redux-core/framework.php
readme.txt

Merge 1.0.77.33 into master

---

.gitignore
README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/functions.php
includes/options/redux-core/assets/css/redux-admin.css
includes/options/redux-core/templates/panel/footer.tpl.php
includes/thirdparty-compatibility.php
readme.txt
templates/features.php

Merge 1.0.77.34 into master

---

README.md
changelog.txt
readme.txt

Merge 1.0.77.37 into master

---

templates/design-manager/swift/style.php

#5243
Merge the code into correct branch

Merge the code into correct branch #5243 

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/admin-script.js
readme.txt
templates/features.php

Merge 1.0.77.40 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
includes/features/performance/performance-functions.php
includes/redirect.php
includes/vendor/tool/Optimizer/Transformer/ServerSideRendering.php
pagebuilder/inc/admin-amp-page-builder.css
readme.txt
templates/features.php

Merge 1.0.77.45 into master

---

accelerated-moblie-pages.php
changelog.txt
classes/class-ampforwp-infinite-scroll.php
components/author-box/author-box.php
components/components-core.php
components/featured-image/featured-image.php
components/loop/loop.php
includes/thirdparty-compatibility.php
readme.txt
templates/features.php

Merge 1.0.77.51 into master

---

README.md
accelerated-moblie-pages.php
changelog.txt
readme.txt
templates/features.php

= 1.0.99.1 (24 September 2024) =
* Fixed: The tag <? is disallowed error in 1.0.99 WITH MENU #5646

ERROR LAST VERSION 1.0.99 WITH TAGS IN MENU #5646
